//! libdeno — embed the Deno runtime in Rust with direct npm support.
//!
//! Runs a JS/TS entry file (or a local package.json project) on the official
//! deno module graph pipeline: npm: specifiers, remote modules, deno.json
//! import maps, jsr:, CJS packages, wasm, .node native addons, web workers
//! and `child_process.fork` are all handled by the graph loader.
//!
//! ```no_run
//! use libdeno::{LibdenoOptions, run};
//!
//! let options = LibdenoOptions {
//!   permissions: vec!["--allow-read=.".into(), "--allow-net=example.com".into()],
//!   args: vec![],
//!   cwd: None,
//!   ..Default::default()
//! };
//! let exit_code = run("app.js", &options).unwrap();
//! ```

mod graph;
mod http;
mod limits;
mod module_loader;
mod node_loader;
mod npm_cache;
mod permission_broker;
mod permissions;
mod runtime;
mod services;
mod subprocess;
mod worker_factory;

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::Arc;

use deno_core::error::AnyError;
use deno_core::ModuleSpecifier;
use deno_runtime::deno_fs::FileSystem;
use deno_runtime::deno_fs::RealFs;
use deno_runtime::deno_inspector_server::MainInspectorSessionChannel;
use deno_runtime::deno_node::NodeExtInitServices;
use deno_runtime::deno_web::BlobStore;
use deno_runtime::deno_web::InMemoryBroadcastChannel;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::worker::WorkerServiceOptions;
use deno_runtime::BootstrapOptions;

pub use permission_broker::{
    install_permission_broker, install_permission_hook, PermissionPrompt, PermissionRequest,
};
pub use runtime::{run_with, LibdenoRuntime};
pub use subprocess::{maybe_handle_child_mode, run_in_subprocess};

use module_loader::GraphModuleLoader;
use node_loader::SimpleNodeRequireLoader;
use permissions::build_permissions;
use services::{RuntimeServices, SharedServices};
use sys_traits::impls::RealSys;
use worker_factory::create_web_worker_factory;

/// Switches the process cwd to `LibdenoOptions.cwd` for the duration of a
/// [`run`], restoring the host's cwd on every exit path (Drop). Without this,
/// scripts would observe the host's cwd (`process.cwd()`/`Deno.cwd()`,
/// relative `Deno.readFile`, relative imports) while permissions and entry
/// resolution use `options.cwd` — a split that silently breaks relative reads
/// under restricted grants.
///
/// The cwd is process-global, so all [`run`]/[`run_in_subprocess`] calls are
/// serialized on [`CWD_LOCK`] while it is in effect.
struct CwdGuard(Option<PathBuf>);

impl CwdGuard {
    fn set(cwd: &Path) -> Self {
        let prev = std::env::current_dir().ok();
        // Canonicalize so scripts observe a consistent cwd on every platform:
        // unix getcwd already resolves aliases (e.g. /var -> /private/var),
        // but Windows GetCurrentDirectory echoes back exactly what was set —
        // including 8.3 short names (e.g. RUNNER~1) from temp paths — so
        // canonicalizing first makes Deno.cwd()/process.cwd() match
        // fs::canonicalize everywhere.
        let target = std::fs::canonicalize(cwd).unwrap_or_else(|_| cwd.to_path_buf());
        if std::env::set_current_dir(&target).is_err() {
            eprintln!(
                "libdeno: failed to chdir to cwd {}; relative paths resolve against the host cwd",
                cwd.display()
            );
            return Self(None);
        }
        Self(prev)
    }
}

impl Drop for CwdGuard {
    fn drop(&mut self) {
        if let Some(prev) = &self.0 {
            let _ = std::env::set_current_dir(prev);
        }
    }
}

/// Serializes in-process [`run`] calls: [`run`] switches the process cwd to
/// `LibdenoOptions.cwd` for its duration (CwdGuard), and the process cwd is
/// global, so concurrent runs would stomp each other. [`run_in_subprocess`]
/// does NOT take this lock — it pins the child's cwd at spawn via
/// `Command::current_dir`, so a long-lived child can never hold the
/// process-global lock. Runs are heavyweight anyway, so serialization costs
/// nothing in practice.
pub(crate) static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

// Generated by build.rs: the V8 snapshot and the residual lazy-load sources.
include!(concat!(env!("OUT_DIR"), "/EXTENSION_RESIDUAL_SOURCES.rs"));
static STARTUP_SNAPSHOT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/CLI_SNAPSHOT.bin"));

/// Options for a single [`run`] invocation.
#[derive(Debug, Clone, Default)]
pub struct LibdenoOptions {
    /// Permission capability strings in `--allow-*` CLI format, e.g.
    /// `"--allow-read=./src"`, `"--allow-net=example.com:8080"`.
    ///
    /// Since v0.2.0 an empty list is a construction error — it no longer
    /// grants anything — unless [`Self::allow_all_permissions`] is set.
    /// Passing any entry restricts the runtime to the declared capabilities; a
    /// flag without a value allows that capability globally. `-A`/`--allow-all`
    /// is equivalent to `allow_all_permissions`.
    pub permissions: Vec<String>,
    /// Explicitly grant every capability (`-A` equivalent). Required to run
    /// scripts with an empty `permissions` list — since v0.2.0 an empty list
    /// no longer grants anything; it is a construction error unless this flag
    /// is set. Use it only for code you trust (see SECURITY.md).
    pub allow_all_permissions: bool,
    /// Interactive permission prompting for non-granted queries, mirroring
    /// `deno run`'s default behavior: the check prints to stderr and reads
    /// allow/deny from stdin (blocking the run while it waits — the upstream
    /// prompter requires a terminal stdin, so headless hosts see every such
    /// query denied without reading).
    ///
    /// With `prompt: true` and an empty `permissions` list, every access is
    /// asked interactively (the v0.2.0 empty-list error does not apply);
    /// with flags, flags grant and everything else is asked.
    pub prompt: bool,
    /// Arguments exposed to the script via `process.argv` (after `argv[0]`).
    pub args: Vec<String>,
    /// Working directory that relative paths (entry, permissions, node_modules
    /// discovery) resolve against. Defaults to the process current directory.
    ///
    /// [`run`] switches the process cwd to this directory for the duration of
    /// the run (restoring it afterwards), so scripts see it as their working
    /// directory too. Concurrent runs in the same process are not supported.
    pub cwd: Option<PathBuf>,
    /// Hard cap on the V8 old-generation heap in bytes (the constraint behind
    /// `--v8-flags=--max-old-space-size`); V8 aborts with OOM when hit.
    pub max_heap_bytes: Option<usize>,
    /// Hard wall-clock limit; on expiry the isolate is force-terminated and
    /// the run fails with [`LibdenoError::Timeout`].
    pub execution_deadline: Option<std::time::Duration>,
}

/// Errors from a [`run`] invocation.
#[derive(Debug, thiserror::Error)]
pub enum LibdenoError {
    /// The entry path could not be resolved to a module.
    #[error("failed to resolve entry module: {0}")]
    Entry(AnyError),
    /// Permission capability strings could not be parsed.
    #[error("invalid permission flags: {0}")]
    Permission(String),
    /// The runtime failed to start or the script failed.
    #[error("{0}")]
    Runtime(#[from] AnyError),
    /// A JS exception escaped the event loop (module execution / event loop).
    #[error("{0}")]
    Core(#[from] deno_core::error::CoreError),
    /// I/O failure in the host (cwd resolution).
    #[error("{0}")]
    Io(#[from] std::io::Error),
    /// A hard time bound fired: the run exceeded
    /// `LibdenoOptions.execution_deadline` and the isolate was
    /// force-terminated, or a [`run_in_subprocess`] handshake timed out (the
    /// host never serviced child mode). The payload is the human-readable
    /// reason.
    #[error("{0}")]
    Timeout(String),
}

// The lifecycle event dispatches (`dispatch_load_event` and friends) return
// `Result<_, Box<JsError>>`; funnel those through the Runtime variant via
// anyhow instead of keeping a dedicated (never-constructed) enum variant.
impl From<Box<deno_core::error::JsError>> for LibdenoError {
    fn from(e: Box<deno_core::error::JsError>) -> Self {
        LibdenoError::Runtime(deno_core::anyhow::Error::new(e))
    }
}

/// Runs `entry` (a file, a directory, or a package.json) to completion and
/// returns the exit code the script requested (0 on normal completion).
///
/// Each call builds its own current-thread runtime and worker. `run` calls
/// are serialized among themselves: the process cwd is switched to
/// `options.cwd` for the duration of the run (and restored afterwards), so
/// scripts observe a consistent working directory. [`run_in_subprocess`] does
/// not take the cwd lock (it pins the child's cwd at spawn instead).
pub fn run(entry: impl AsRef<Path>, options: &LibdenoOptions) -> Result<i32, LibdenoError> {
    // The process cwd is process-global; serialize so a concurrent run cannot
    // observe another run's cwd (see CWD_LOCK).
    let _lock = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    // Capture the entry-time child-IPC marker (and write it back so fork children inherit it).
    limits::capture_spawned_ipc_marker();
    // Building a runtime inside a tokio runtime panics; report instead of
    // taking down the host. Embedders calling run() from an async task should
    // use run_in_subprocess (or spawn a thread).
    if tokio::runtime::Handle::try_current().is_ok() {
        return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
            "libdeno::run() cannot be called from inside a tokio runtime; \
             call it from a non-async context or use run_in_subprocess"
        )));
    }
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)))?;
    runtime.block_on(run_inner(entry.as_ref(), options))
}

async fn run_inner(entry: &Path, options: &LibdenoOptions) -> Result<i32, LibdenoError> {
    // Canonicalize once so entry resolution, permission grants, node_modules
    // discovery and the process cwd all agree: unix getcwd already
    // canonicalizes (e.g. /var -> /private/var) and CwdGuard canonicalizes
    // before chdir, so a symlinked options.cwd would otherwise split
    // Deno.cwd() (canonical) from relative grants/entry (aliased).
    let cwd_raw = options.cwd.clone().unwrap_or(std::env::current_dir()?);
    let cwd = std::fs::canonicalize(&cwd_raw).unwrap_or(cwd_raw);
    // Deliberately keep this guard: `run_with` goes straight into
    // `run_inner_with` (which sets a second guard), and `run_inner` builds
    // SharedServices while this guard is in effect. The double guard is
    // redundant but correct — merging them is not worth the micro-refactor.
    let _cwd_guard = CwdGuard::set(&cwd);
    let main_module = resolve_entry(entry, &cwd).map_err(LibdenoError::Entry)?;
    let config_start_paths = main_module
        .to_file_path()
        .ok()
        .and_then(|p| p.parent().map(|d| vec![d.to_path_buf()]))
        .unwrap_or_else(|| vec![cwd.clone()]);
    let shared = SharedServices::new(cwd.clone(), config_start_paths)
        .await
        .map_err(LibdenoError::Runtime)?;
    run_inner_with(shared, cwd, entry, options).await
}

/// The per-run half of a [`run`]/[`run_with`] against an already-built
/// resolver stack: the permission-bound services and the run lifecycle.
pub(crate) async fn run_inner_with(
    shared: Arc<SharedServices>,
    cwd: PathBuf,
    entry: &Path,
    options: &LibdenoOptions,
) -> Result<i32, LibdenoError> {
    // rustls needs an explicit CryptoProvider (aws-lc-rs and ring are both
    // enabled in the dep graph); the deno CLI does the same. Only install when
    // the host has not already set one — install_default returns Err exactly
    // when a provider is already installed, so with this guard the result can
    // no longer fail silently.
    if deno_runtime::deno_tls::rustls::crypto::CryptoProvider::get_default().is_none() {
        let _ = deno_runtime::deno_tls::rustls::crypto::CryptoProvider::install_default(
            deno_runtime::deno_tls::rustls::crypto::aws_lc_rs::default_provider(),
        );
    }
    let _cwd_guard = CwdGuard::set(&cwd);
    let main_module = resolve_entry(entry, &cwd).map_err(LibdenoError::Entry)?;

    let fs: Arc<dyn FileSystem> = Arc::new(RealFs);
    let permission_parser =
        Arc::new(deno_runtime::deno_permissions::RuntimePermissionDescriptorParser::new(RealSys));
    let permissions = build_permissions(
        &options.permissions,
        options.allow_all_permissions,
        options.prompt,
        permission_parser.clone(),
        &cwd,
    )?;
    let services = Arc::new(
        RuntimeServices::new(shared, cwd, permissions.clone()).map_err(LibdenoError::Runtime)?,
    );

    // has_node_modules_dir must come AFTER RuntimeServices::new: that runs
    // initialize_npm_resolution_if_managed, which decides Managed vs BYONM.
    let has_node_modules_dir = {
        use deno_resolver::npm::NpmResolver;
        match services
            .shared
            .resolver_factory
            .npm_resolver()
            .map_err(LibdenoError::Runtime)?
        {
            NpmResolver::Managed(managed) => managed.root_node_modules_path().is_some(),
            NpmResolver::Byonm(byonm) => byonm.root_node_modules_path().is_some(),
        }
    };

    let module_loader: Rc<dyn deno_core::ModuleLoader> = Rc::new(GraphModuleLoader::new(
        services.clone(),
        permissions.clone(),
    ));

    let node_resolver = services.shared.resolver_factory.node_resolver()?.clone();
    let pkg_json_resolver = services.shared.resolver_factory.pkg_json_resolver().clone();
    let cjs_tracker = services.shared.resolver_factory.cjs_tracker()?.clone();
    let in_npm_pkg_checker = services
        .shared
        .resolver_factory
        .in_npm_package_checker()?
        .clone();
    let node_require_loader: deno_runtime::deno_node::NodeRequireLoaderRc = Rc::new(
        SimpleNodeRequireLoader::new(cjs_tracker, in_npm_pkg_checker),
    );
    let node_sys = services.shared.sys.clone();
    let node_services = Some(NodeExtInitServices {
        node_require_loader: node_require_loader.clone(),
        node_resolver: node_resolver.clone(),
        pkg_json_resolver: pkg_json_resolver.clone(),
        sys: node_sys.clone(),
    });

    let blob_store = BlobStore::default_arc();
    let broadcast_channel = InMemoryBroadcastChannel::default();
    // Unstable APIs enabled by default (kv, cron, ffi, webgpu, worker-options)
    // — an "everything enabled" stance like `deno run --unstable`; an embedded
    // runtime has no flag surface. worker-options gates the worker
    // `permissions`/`env`/`net` options in `new Worker(...)` (op_create_worker
    // exits the process if the feature is off), so it must stay enabled for
    // worker permission narrowing to work. JS namespace IDs and FeatureChecker
    // names must stay in sync.
    const ENABLED_FEATURES: &[&str] = &["kv", "cron", "ffi", "webgpu", "worker-options"];
    let feature_checker = {
        let mut fc = deno_runtime::FeatureChecker::default();
        for feature in ENABLED_FEATURES {
            fc.enable_feature(feature);
        }
        Arc::new(fc)
    };
    let unstable_ids: Vec<i32> = deno_features::UNSTABLE_FEATURES
        .iter()
        .filter(|f| ENABLED_FEATURES.contains(&f.name))
        .map(|f| f.id)
        .collect();

    let worker_services = WorkerServiceOptions {
        blob_store: blob_store.clone(),
        broadcast_channel: broadcast_channel.clone(),
        deno_rt_native_addon_loader: None,
        feature_checker: feature_checker.clone(),
        fs: fs.clone(),
        module_loader: module_loader.clone(),
        node_services: node_services.clone(),
        npm_process_state_provider: Some(services.shared.npm_process_state_provider.clone()),
        permissions: permissions.clone(),
        root_cert_store_provider: None,
        fetch_dns_resolver: deno_runtime::deno_fetch::dns::Resolver::default(),
        shared_array_buffer_store: None,
        compiled_wasm_module_store: None,
        // In-process V8 code cache, keyed by specifier + source hash (limits.rs).
        v8_code_cache: Some(limits::in_process_code_cache()),
        bundle_provider: None,
    };

    // Must match deno_runtime's release tag: scripts feature-detect
    // Deno.version.deno. deno_runtime 0.265.0 == Deno v2.9.5.
    const DENO_VERSION: &str = "2.9.5";

    let main_bootstrap = BootstrapOptions {
        deno_version: DENO_VERSION.to_string(),
        user_agent: format!(
            "libdeno/{}/Deno/{}",
            env!("CARGO_PKG_VERSION"),
            DENO_VERSION
        ),
        has_node_modules_dir,
        location: Some(main_module.clone()),
        args: options.args.clone(),
        unstable_features: unstable_ids,
        // fork() IPC pipe; gated on the marker captured at run() entry (limits.rs).
        node_ipc_init: limits::node_ipc_init(),
        ..Default::default()
    };

    // Factory for `new Worker(...)`; nested workers reuse the same loader,
    // services and snapshot, and inherit the main worker's heap cap.
    let create_web_worker_cb: Arc<deno_runtime::ops::worker_host::CreateWebWorkerCb> =
        create_web_worker_factory(
            blob_store,
            broadcast_channel,
            feature_checker,
            fs.clone(),
            services.clone(),
            MainInspectorSessionChannel::default(),
            main_bootstrap.clone(),
            options.max_heap_bytes,
        )?;

    let worker_options = WorkerOptions {
        bootstrap: main_bootstrap,
        create_web_worker_cb,
        extensions: vec![],
        startup_snapshot: Some(STARTUP_SNAPSHOT),
        residual_lazy_js_sources: RESIDUAL_LAZY_JS,
        residual_lazy_esm_sources: RESIDUAL_LAZY_ESM,
        create_params: limits::isolate_create_params(options.max_heap_bytes),
        ..Default::default()
    };

    let mut worker =
        MainWorker::bootstrap_from_options(&main_module, worker_services, worker_options);

    // Intercept Deno.exit: a WatcherExitHandle in the OpState makes op_exit
    // terminate the isolate (the CLI's --watch path); ExitCode op state carries n.
    let isolate_handle = worker.js_runtime.v8_isolate().thread_safe_handle();
    worker
        .js_runtime
        .op_state()
        .borrow_mut()
        .put(deno_runtime::deno_os::WatcherExitHandle(
            isolate_handle.clone(),
        ));

    let run_result = match limits::run_worker(
        &mut worker,
        &main_module,
        options.execution_deadline,
        isolate_handle.clone(),
    )
    .await
    {
        Ok(result) => result,
        // Deadline fired: isolate terminated; cwd lock releases on return.
        Err(deadline) => {
            return Err(LibdenoError::Timeout(format!(
                "execution deadline of {deadline:?} exceeded; isolate terminated"
            )))
        }
    };

    let exit_code = match run_result {
        Ok(()) => worker.exit_code(),
        Err(_) if crate::runtime::has_watcher_exited(&worker) => worker.exit_code(),
        Err(e) => return Err(e),
    };
    // Cache the resolved npm snapshot (managed, no lockfile) only now: the
    // graph build has populated the resolution, so the snapshot is real.
    services.save_npm_snapshot_cache();
    Ok(exit_code)
}

/// Resolve the entry module: a file path, or a directory / package.json whose
/// `main` (default `index.js`) is used.
fn resolve_entry(path: &Path, cwd: &Path) -> Result<ModuleSpecifier, AnyError> {
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    };
    let file_path = if path.is_dir() {
        let pkg = path.join("package.json");
        if pkg.exists() {
            package_main(&pkg)?
        } else {
            path.join("index.js")
        }
    } else if path.file_name().and_then(|n| n.to_str()) == Some("package.json") {
        package_main(&path)?
    } else {
        path
    };
    ModuleSpecifier::from_file_path(&file_path)
        .map_err(|_| deno_core::anyhow::anyhow!("Invalid entry file path: {}", file_path.display()))
}

fn package_main(pkg_path: &Path) -> Result<PathBuf, AnyError> {
    let text = std::fs::read_to_string(pkg_path)?;
    let json: deno_core::serde_json::Value = deno_core::serde_json::from_str(&text)?;
    let main = json
        .get("main")
        .and_then(|v| v.as_str())
        .unwrap_or("index.js");
    let dir = pkg_path.parent().unwrap_or(Path::new("."));
    let main_path = dir.join(main);
    // Reject `main` values that escape the package directory. `Path::join`
    // replaces the base for absolute paths (strip_prefix fails, caught
    // directly); relative `..` components are normalized lexically — a `..`
    // that walks back into the package (`lib/../index.js`) is fine, one that
    // pops above `dir` (`../escape.js`) is not. (Symlinked components are not
    // resolved: the entry directory is host-selected, so this is a sanity
    // guard, not a boundary.)
    use std::path::Component;
    let escaped = match main_path.strip_prefix(dir) {
        Err(_) => true,
        Ok(rest) => {
            let mut depth: i64 = 0;
            let mut escaped = false;
            for c in rest.components() {
                match c {
                    Component::Normal(_) => depth += 1,
                    Component::CurDir => {}
                    Component::ParentDir => {
                        if depth == 0 {
                            escaped = true;
                            break;
                        }
                        depth -= 1;
                    }
                    Component::RootDir | Component::Prefix(_) => {
                        escaped = true;
                        break;
                    }
                }
            }
            escaped
        }
    };
    if escaped {
        return Err(deno_core::anyhow::anyhow!(
            "package.json `main` field {main:?} escapes the package directory"
        ));
    }
    Ok(main_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("libdeno-test-{}-{}", std::process::id(), name));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn resolve_entry_file() {
        let dir = temp_dir("entry-file");
        let file = dir.join("app.js");
        std::fs::write(&file, "").unwrap();
        let spec = resolve_entry(&file, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), file);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_directory_uses_package_main() {
        let dir = temp_dir("entry-dir-pkg");
        std::fs::write(
            dir.join("package.json"),
            r#"{"name":"app","main":"src/main.js"}"#,
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(dir.join("src/main.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("src/main.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_directory_defaults_to_index_js() {
        let dir = temp_dir("entry-dir-default");
        std::fs::write(dir.join("index.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("index.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_package_json_directly() {
        let dir = temp_dir("entry-pkgjson");
        std::fs::write(dir.join("package.json"), r#"{"main":"lib/index.js"}"#).unwrap();
        std::fs::create_dir_all(dir.join("lib")).unwrap();
        std::fs::write(dir.join("lib/index.js"), "").unwrap();
        let spec = resolve_entry(&dir.join("package.json"), &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("lib/index.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_relative_path_joins_cwd() {
        let dir = temp_dir("entry-relative");
        std::fs::write(dir.join("app.ts"), "").unwrap();
        let spec = resolve_entry(Path::new("app.ts"), &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("app.ts"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_escaping_the_package_dir_is_rejected() {
        let dir = temp_dir("pkg-escape");
        std::fs::write(dir.join("package.json"), r#"{"main":"../escape.js"}"#).unwrap();
        let err = resolve_entry(&dir, &dir).unwrap_err();
        assert!(
            err.to_string().contains("escapes"),
            "expected an escape rejection, got: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_internal_dotdot_is_allowed() {
        // A `..` that normalizes back inside the package (`src/../lib/index.js`)
        // is not an escape: the guard rejects only paths that pop above the
        // package directory, not every ParentDir component.
        let dir = temp_dir("pkg-internal-dotdot");
        std::fs::write(
            dir.join("package.json"),
            r#"{"main":"src/../lib/index.js"}"#,
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("lib")).unwrap();
        std::fs::write(dir.join("lib/index.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(
            spec.to_file_path().unwrap(),
            dir.join("src/../lib/index.js")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_absolute_main_is_rejected() {
        // `Path::join` replaces the base for absolute paths, so an absolute
        // `main` must be rejected as an escape (strip_prefix fails).
        let dir = temp_dir("pkg-abs-main");
        std::fs::write(dir.join("package.json"), r#"{"main":"/etc/passwd"}"#).unwrap();
        let err = resolve_entry(&dir, &dir).unwrap_err();
        assert!(
            err.to_string().contains("escapes"),
            "expected an escape rejection, got: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
