//! libdeno — embed the Deno runtime in Rust with direct npm support.
//!
//! Runs a JS/TS entry file (or a local package.json project) on the official
//! deno module graph pipeline: npm: specifiers, remote modules, deno.json
//! import maps, jsr:, CJS packages, wasm, .node native addons, web workers
//! and `child_process.fork` are all handled by the graph loader.
//!
//! ```no_run
//! use libdeno::{LibdenoOptions, run};
//!
//! let options = LibdenoOptions {
//!   permissions: vec!["--allow-read=.".into(), "--allow-net=example.com".into()],
//!   args: vec![],
//!   cwd: None,
//!   ..Default::default()
//! };
//! let exit_code = run("app.js", &options).unwrap();
//! ```

mod analysis_cache;
mod graph;
mod http;
mod limits;
mod module_loader;
mod node_loader;
mod npm_cache;
mod output;
mod permission_broker;
mod permissions;
// Public so `libdeno::runtime::run_with_output` (capture on a reusable
// resolver stack) is reachable; the root re-exports `run_with` /
// `LibdenoRuntime` for the common paths.
pub mod runtime;
mod services;
mod subprocess;
mod worker_factory;

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::Arc;

use deno_core::error::AnyError;
use deno_core::ModuleSpecifier;
use deno_runtime::deno_fs::FileSystem;
use deno_runtime::deno_fs::RealFs;
use deno_runtime::deno_inspector_server::MainInspectorSessionChannel;
use deno_runtime::deno_node::NodeExtInitServices;
use deno_runtime::deno_web::BlobStore;
use deno_runtime::deno_web::InMemoryBroadcastChannel;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::worker::WorkerServiceOptions;
use deno_runtime::BootstrapOptions;

pub use permission_broker::{
    install_permission_broker, install_permission_hook, PermissionPrompt, PermissionRequest,
};
pub use runtime::{run_with, LibdenoRuntime};
pub use subprocess::{maybe_handle_child_mode, run_in_subprocess};

use module_loader::GraphModuleLoader;
use node_loader::SimpleNodeRequireLoader;
use permissions::build_permissions;
use services::{RuntimeServices, SharedServices};
use sys_traits::impls::RealSys;
use worker_factory::create_web_worker_factory;

/// Switches the process cwd to `LibdenoOptions.cwd` for the duration of a
/// [`run`], restoring the host's cwd on every exit path (Drop). Without this,
/// scripts would observe the host's cwd (`process.cwd()`/`Deno.cwd()`,
/// relative `Deno.readFile`, relative imports) while permissions and entry
/// resolution use `options.cwd` — a split that silently breaks relative reads
/// under restricted grants.
///
/// The cwd is process-global, so all [`run`]/[`run_in_subprocess`] calls are
/// serialized on [`CWD_LOCK`] while it is in effect.
struct CwdGuard(Option<PathBuf>);

impl CwdGuard {
    fn set(cwd: &Path) -> Self {
        let prev = std::env::current_dir().ok();
        // Canonicalize so scripts observe a consistent cwd on every platform:
        // unix getcwd already resolves aliases (e.g. /var -> /private/var),
        // but Windows GetCurrentDirectory echoes back exactly what was set —
        // including 8.3 short names (e.g. RUNNER~1) from temp paths — so
        // canonicalizing first makes Deno.cwd()/process.cwd() match
        // fs::canonicalize everywhere.
        let target = std::fs::canonicalize(cwd).unwrap_or_else(|_| cwd.to_path_buf());
        if std::env::set_current_dir(&target).is_err() {
            eprintln!(
                "libdeno: failed to chdir to cwd {}; relative paths resolve against the host cwd",
                cwd.display()
            );
            return Self(None);
        }
        Self(prev)
    }
}

impl Drop for CwdGuard {
    fn drop(&mut self) {
        if let Some(prev) = &self.0 {
            let _ = std::env::set_current_dir(prev);
        }
    }
}

/// Serializes in-process [`run`] calls: [`run`] switches the process cwd to
/// `LibdenoOptions.cwd` for its duration (CwdGuard), and the process cwd is
/// global, so concurrent runs would stomp each other. [`run_in_subprocess`]
/// does NOT take this lock — it pins the child's cwd at spawn via
/// `Command::current_dir`, so a long-lived child can never hold the
/// process-global lock. Runs are heavyweight anyway, so serialization costs
/// nothing in practice.
pub(crate) static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

// Generated by build.rs: the V8 snapshot and the residual lazy-load sources.
include!(concat!(env!("OUT_DIR"), "/EXTENSION_RESIDUAL_SOURCES.rs"));
static STARTUP_SNAPSHOT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/CLI_SNAPSHOT.bin"));

/// Options for a single [`run`] invocation.
#[derive(Debug, Clone, Default)]
pub struct LibdenoOptions {
    /// Permission capability strings in `--allow-*` CLI format, e.g.
    /// `"--allow-read=./src"`, `"--allow-net=example.com:8080"`.
    ///
    /// Since v0.2.0 an empty list is a construction error — it no longer
    /// grants anything — unless [`Self::allow_all_permissions`] is set.
    /// Passing any entry restricts the runtime to the declared capabilities; a
    /// flag without a value allows that capability globally. `-A`/`--allow-all`
    /// is equivalent to `allow_all_permissions`.
    pub permissions: Vec<String>,
    /// Explicitly grant every capability (`-A` equivalent). Required to run
    /// scripts with an empty `permissions` list — since v0.2.0 an empty list
    /// no longer grants anything; it is a construction error unless this flag
    /// is set. Use it only for code you trust (see SECURITY.md).
    pub allow_all_permissions: bool,
    /// Interactive permission prompting for non-granted queries, mirroring
    /// `deno run`'s default behavior: the check prints to stderr and reads
    /// allow/deny from stdin (blocking the run while it waits — the upstream
    /// prompter requires a terminal stdin, so headless hosts see every such
    /// query denied without reading).
    ///
    /// With `prompt: true` and an empty `permissions` list, every access is
    /// asked interactively (the v0.2.0 empty-list error does not apply);
    /// with flags, flags grant and everything else is asked.
    pub prompt: bool,
    /// Arguments exposed to the script via `process.argv` (after `argv[0]`).
    pub args: Vec<String>,
    /// Working directory that relative paths (entry, permissions, node_modules
    /// discovery) resolve against. Defaults to the process current directory.
    ///
    /// [`run`] switches the process cwd to this directory for the duration of
    /// the run (restoring it afterwards), so scripts see it as their working
    /// directory too. Concurrent runs in the same process are not supported.
    pub cwd: Option<PathBuf>,
    /// Hard cap on the V8 old-generation heap in bytes (the constraint behind
    /// `--v8-flags=--max-old-space-size`); V8 aborts with OOM when hit.
    pub max_heap_bytes: Option<usize>,
    /// Hard wall-clock limit; on expiry the isolate is force-terminated and
    /// the run fails with [`LibdenoError::Timeout`].
    pub execution_deadline: Option<std::time::Duration>,
    /// Redirect the script's stdout (fd 1, e.g. `console.log`) into
    /// [`RunOutput::stdout`] instead of the host's terminal. Off by default
    /// (output passes through). While active the redirection is
    /// process-global: other host threads printing to stdout during the run
    /// are captured too (runs are serialized on the internal cwd lock).
    pub capture_stdout: bool,
    /// Redirect the script's stderr (fd 2, e.g. `console.error`) into
    /// [`RunOutput::stderr`]; same semantics and caveats as
    /// [`Self::capture_stdout`].
    pub capture_stderr: bool,
    /// Cap on captured output per stream (stdout and stderr each get this
    /// budget). When a stream exceeds it, capture stops, the excess is
    /// dropped, and [`RunOutput::capture_truncated`] is set — a verbose or
    /// hostile script can no longer grow host memory without limit. `None`
    /// (default) captures without a bound.
    pub max_capture_bytes: Option<usize>,
    /// Runtime feature flags exposed to the script, overriding the default
    /// set (`kv`, `cron`, `ffi`, `webgpu`, `worker-options`). Feature names
    /// must be valid deno unstable-feature names (see deno's
    /// `--unstable-*` flags); they gate which JS namespace IDs and feature
    /// checks are wired into the runtime. `None` (default) enables the
    /// default set. An embedder running untrusted plugins can shrink the
    /// surface (e.g. `Some(vec!["ffi".into()])`); the ops themselves stay
    /// permission-gated regardless. `worker-options` is always enabled even
    /// when omitted from a custom set — without it `new Worker(...)` with
    /// worker options terminates the host process, which a plugin must never
    /// be able to trigger.
    pub features: Option<Vec<String>>,
}

/// The result of a [`run_with_output`] invocation.
#[derive(Debug, Clone, Default)]
pub struct RunOutput {
    /// The exit code the script requested (0 on normal completion).
    pub exit_code: i32,
    /// Captured stdout bytes; empty unless [`LibdenoOptions::capture_stdout`]
    /// was set. Unbounded: a verbose or hostile script grows this without
    /// limit for the run's duration — bound the script, or set
    /// [`LibdenoOptions::execution_deadline`].
    pub stdout: Vec<u8>,
    /// Captured stderr bytes; empty unless [`LibdenoOptions::capture_stderr`]
    /// was set. Same unbounded-growth caveat as [`Self::stdout`].
    pub stderr: Vec<u8>,
    /// True when a captured stream hit [`LibdenoOptions::max_capture_bytes`]
    /// and was truncated. False when no capture was requested or when both
    /// streams fit their budgets.
    pub capture_truncated: bool,
}

/// Errors from a [`run`] invocation.
#[derive(Debug, thiserror::Error)]
pub enum LibdenoError {
    /// The entry path could not be resolved to a module.
    #[error("failed to resolve entry module: {0}")]
    Entry(AnyError),
    /// Permission capability strings could not be parsed.
    #[error("invalid permission flags: {0}")]
    Permission(String),
    /// Host/configuration-level problems: options that cannot be turned into a
    /// valid runtime configuration as given (e.g. an empty permission list
    /// without `allow_all_permissions`, which since v0.2.0 grants nothing).
    /// Distinguished from [`Self::Permission`] so embedders can tell "fix your
    /// option values" apart from "the dependency environment is broken".
    #[error("{0}")]
    Configuration(String),
    /// The runtime failed to start or the script failed.
    #[error("{0}")]
    Runtime(#[from] AnyError),
    /// A JS exception escaped the event loop (module execution / event loop).
    #[error("{0}")]
    Core(#[from] deno_core::error::CoreError),
    /// I/O failure in the host (cwd resolution).
    #[error("{0}")]
    Io(#[from] std::io::Error),
    /// A hard time bound fired: the run exceeded
    /// `LibdenoOptions.execution_deadline` and the isolate was
    /// force-terminated, or a [`run_in_subprocess`] handshake timed out (the
    /// host never serviced child mode). The payload is the human-readable
    /// reason.
    #[error("{0}")]
    Timeout(String),
}

// The lifecycle event dispatches (`dispatch_load_event` and friends) return
// `Result<_, Box<JsError>>`; funnel those through the Runtime variant via
// anyhow instead of keeping a dedicated (never-constructed) enum variant.
impl From<Box<deno_core::error::JsError>> for LibdenoError {
    fn from(e: Box<deno_core::error::JsError>) -> Self {
        LibdenoError::Runtime(deno_core::anyhow::Error::new(e))
    }
}

/// Runs `entry` (a file, a directory, or a package.json) to completion and
/// returns the exit code the script requested (0 on normal completion).
///
/// Each call builds its own current-thread runtime and worker. `run` calls
/// are serialized among themselves: the process cwd is switched to
/// `options.cwd` for the duration of the run (and restored afterwards), so
/// scripts observe a consistent working directory. [`run_in_subprocess`] does
/// not take the cwd lock (it pins the child's cwd at spawn instead).
pub fn run(entry: impl AsRef<Path>, options: &LibdenoOptions) -> Result<i32, LibdenoError> {
    run_with_output(entry, options).map(|o| o.exit_code)
}

/// Runs `entry` to completion, returning the exit code together with the
/// script's stdout/stderr when [`LibdenoOptions::capture_stdout`] /
/// [`LibdenoOptions::capture_stderr`] are set.
///
/// Semantics match [`run`], including the tokio re-entry handling: building a
/// tokio runtime inside a tokio runtime panics, so when called from inside a
/// tokio context the run executes on a fresh thread (exactly the
/// `std::thread::spawn + join` escape async hosts previously had to build
/// themselves). The internal cwd lock is held across that thread's lifetime,
/// so concurrent runs remain serialized.
pub fn run_with_output(
    entry: impl AsRef<Path>,
    options: &LibdenoOptions,
) -> Result<RunOutput, LibdenoError> {
    // The process cwd is process-global; serialize so a concurrent run cannot
    // observe another run's cwd (see CWD_LOCK).
    let _lock = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    // Capture the entry-time child-IPC marker (and write it back so fork children inherit it).
    limits::capture_spawned_ipc_marker();
    let entry = entry.as_ref().to_path_buf();
    let options = options.clone();
    if tokio::runtime::Handle::try_current().is_ok() {
        std::thread::spawn(move || run_sync_output(&entry, &options))
            .join()
            .map_err(|_| {
                LibdenoError::Runtime(deno_core::anyhow::anyhow!("libdeno worker thread panicked"))
            })?
    } else {
        run_sync_output(&entry, &options)
    }
}

fn run_sync_output(entry: &Path, options: &LibdenoOptions) -> Result<RunOutput, LibdenoError> {
    // Windows: Rust std's stdout/stderr write via GetStdHandle, bypassing the
    // CRT fd that dup2 redirects, so console output cannot be captured
    // in-process there. Report a clean error instead of silently returning
    // empty buffers.
    #[cfg(windows)]
    if options.capture_stdout || options.capture_stderr {
        return Err(LibdenoError::Configuration(
            "output capture is not supported on Windows (std stdout/stderr \
             bypass the redirected CRT fd); use run_in_subprocess and pipe \
             the child's output instead"
                .to_string(),
        ));
    }
    let capture = output::OutputCapture::new(
        options.capture_stdout,
        options.capture_stderr,
        options.max_capture_bytes,
    )
    .map_err(LibdenoError::Io)?;
    let result = run_sync(entry, options);
    let (stdout, stderr, capture_truncated) = capture.finish();
    Ok(RunOutput {
        exit_code: result?,
        stdout,
        stderr,
        capture_truncated,
    })
}

/// FeatureChecker::enable_feature requires `&'static str`, but a host's
/// feature list arrives as owned `String`s. Leak one `'static` copy per
/// *unique* set and cache it: a long-lived host running the same features
/// leaks exactly once, not once per run.
fn static_feature_names(features: &[String]) -> Vec<&'static str> {
    static CACHE: std::sync::Mutex<Vec<(Vec<String>, Vec<&'static str>)>> =
        std::sync::Mutex::new(Vec::new());
    let mut cache = CACHE.lock().unwrap_or_else(|e| e.into_inner());
    if let Some((_, names)) = cache.iter().find(|(key, _)| key == features) {
        return names.clone();
    }
    let mut seen = std::collections::HashSet::new();
    let names: Vec<&'static str> = features
        .iter()
        // Deduplicate: FeatureChecker::enable_feature asserts on a duplicate
        // insert and would panic the host process.
        .filter(|s| seen.insert(s.as_str()))
        .map(|s| Box::leak(s.clone().into_boxed_str()) as &'static str)
        .collect();
    cache.push((features.to_vec(), names.clone()));
    names
}

/// The actual run: a fresh current-thread runtime and the run lifecycle. Must
/// not be called from inside a tokio runtime (tokio panics on nested
/// runtimes); [`run_with_output`] routes such callers onto a fresh thread
/// first.
fn run_sync(entry: &Path, options: &LibdenoOptions) -> Result<i32, LibdenoError> {
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)))?;
    runtime.block_on(run_inner(entry, options))
}

async fn run_inner(entry: &Path, options: &LibdenoOptions) -> Result<i32, LibdenoError> {
    // Canonicalize once so entry resolution, permission grants, node_modules
    // discovery and the process cwd all agree: unix getcwd already
    // canonicalizes (e.g. /var -> /private/var) and CwdGuard canonicalizes
    // before chdir, so a symlinked options.cwd would otherwise split
    // Deno.cwd() (canonical) from relative grants/entry (aliased).
    let cwd_raw = options.cwd.clone().unwrap_or(std::env::current_dir()?);
    let cwd = std::fs::canonicalize(&cwd_raw).unwrap_or(cwd_raw);
    // Deliberately keep this guard: `run_with` goes straight into
    // `run_inner_with` (which sets a second guard), and `run_inner` builds
    // SharedServices while this guard is in effect. The double guard is
    // redundant but correct — merging them is not worth the micro-refactor.
    let _cwd_guard = CwdGuard::set(&cwd);
    let main_module = resolve_entry(entry, &cwd).map_err(LibdenoError::Entry)?;
    let config_start_paths = main_module
        .to_file_path()
        .ok()
        .and_then(|p| p.parent().map(|d| vec![d.to_path_buf()]))
        .unwrap_or_else(|| vec![cwd.clone()]);
    let shared = SharedServices::new(cwd.clone(), config_start_paths)
        .await
        .map_err(LibdenoError::Runtime)?;
    run_inner_with(shared, cwd, entry, options).await
}

/// The per-run half of a [`run`]/[`run_with`] against an already-built
/// resolver stack: the permission-bound services and the run lifecycle.
pub(crate) async fn run_inner_with(
    shared: Arc<SharedServices>,
    cwd: PathBuf,
    entry: &Path,
    options: &LibdenoOptions,
) -> Result<i32, LibdenoError> {
    // rustls needs an explicit CryptoProvider (aws-lc-rs and ring are both
    // enabled in the dep graph); the deno CLI does the same. Only install when
    // the host has not already set one — install_default returns Err exactly
    // when a provider is already installed, so with this guard the result can
    // no longer fail silently.
    if deno_runtime::deno_tls::rustls::crypto::CryptoProvider::get_default().is_none() {
        let _ = deno_runtime::deno_tls::rustls::crypto::CryptoProvider::install_default(
            deno_runtime::deno_tls::rustls::crypto::aws_lc_rs::default_provider(),
        );
    }
    let _cwd_guard = CwdGuard::set(&cwd);
    let main_module = resolve_entry(entry, &cwd).map_err(LibdenoError::Entry)?;

    let fs: Arc<dyn FileSystem> = Arc::new(RealFs);
    let permission_parser =
        Arc::new(deno_runtime::deno_permissions::RuntimePermissionDescriptorParser::new(RealSys));
    let permissions = build_permissions(
        &options.permissions,
        options.allow_all_permissions,
        options.prompt,
        permission_parser.clone(),
        &cwd,
    )?;
    let services = Arc::new(
        RuntimeServices::new(shared, cwd, permissions.clone()).map_err(LibdenoError::Runtime)?,
    );

    // has_node_modules_dir must come AFTER RuntimeServices::new: that runs
    // initialize_npm_resolution_if_managed, which decides Managed vs BYONM.
    let has_node_modules_dir = {
        use deno_resolver::npm::NpmResolver;
        match services
            .shared
            .resolver_factory
            .npm_resolver()
            .map_err(LibdenoError::Runtime)?
        {
            NpmResolver::Managed(managed) => managed.root_node_modules_path().is_some(),
            NpmResolver::Byonm(byonm) => byonm.root_node_modules_path().is_some(),
        }
    };

    let module_loader: Rc<dyn deno_core::ModuleLoader> = Rc::new(GraphModuleLoader::new(
        services.clone(),
        permissions.clone(),
    ));

    let node_resolver = services.shared.resolver_factory.node_resolver()?.clone();
    let pkg_json_resolver = services.shared.resolver_factory.pkg_json_resolver().clone();
    let cjs_tracker = services.shared.resolver_factory.cjs_tracker()?.clone();
    let in_npm_pkg_checker = services
        .shared
        .resolver_factory
        .in_npm_package_checker()?
        .clone();
    let node_require_loader: deno_runtime::deno_node::NodeRequireLoaderRc = Rc::new(
        SimpleNodeRequireLoader::new(cjs_tracker, in_npm_pkg_checker),
    );
    let node_sys = services.shared.sys.clone();
    let node_services = Some(NodeExtInitServices {
        node_require_loader: node_require_loader.clone(),
        node_resolver: node_resolver.clone(),
        pkg_json_resolver: pkg_json_resolver.clone(),
        sys: node_sys.clone(),
    });

    let blob_store = BlobStore::default_arc();
    let broadcast_channel = InMemoryBroadcastChannel::default();
    // Default: "everything enabled" like `deno run --unstable` (kv, cron,
    // ffi, webgpu, worker-options) — an embedded runtime has no flag surface
    // unless the host opts in via `LibdenoOptions.features`. worker-options
    // gates the worker `permissions`/`env`/`net` options in `new Worker(...)`
    // (op_create_worker exits the process if the feature is off), so a
    // custom set that omits it breaks worker permission narrowing. JS
    // namespace IDs and FeatureChecker names must stay in sync.
    const ENABLED_FEATURES: &[&str] = &["kv", "cron", "ffi", "webgpu", "worker-options"];
    // Unknown feature names would be silent no-ops; fail loudly instead,
    // consistent with how other bad option values surface (Configuration).
    if let Some(features) = &options.features {
        let valid: std::collections::HashSet<&str> = deno_features::UNSTABLE_FEATURES
            .iter()
            .map(|f| f.name)
            .collect();
        if let Some(bad) = features.iter().find(|f| !valid.contains(f.as_str())) {
            return Err(LibdenoError::Configuration(format!(
                "unknown runtime feature: {bad}"
            )));
        }
    }
    let enabled_features: Vec<&str> = match &options.features {
        Some(features) => {
            // worker-options is force-enabled regardless of the custom set:
            // it gates the worker `permissions`/`env`/`net` options, and
            // op_create_worker EXITS the process when the feature is off —
            // a host shrinking the surface for untrusted plugins must not
            // hand a plugin a way to kill the host.
            let mut names = static_feature_names(features);
            if !names.contains(&"worker-options") {
                names.push("worker-options");
            }
            names
        }
        None => ENABLED_FEATURES.to_vec(),
    };
    let feature_checker = {
        let mut fc = deno_runtime::FeatureChecker::default();
        for feature in &enabled_features {
            fc.enable_feature(feature);
        }
        Arc::new(fc)
    };
    let unstable_ids: Vec<i32> = deno_features::UNSTABLE_FEATURES
        .iter()
        .filter(|f| enabled_features.contains(&f.name))
        .map(|f| f.id)
        .collect();

    let worker_services = WorkerServiceOptions {
        blob_store: blob_store.clone(),
        broadcast_channel: broadcast_channel.clone(),
        deno_rt_native_addon_loader: None,
        feature_checker: feature_checker.clone(),
        fs: fs.clone(),
        module_loader: module_loader.clone(),
        node_services: node_services.clone(),
        npm_process_state_provider: Some(services.shared.npm_process_state_provider.clone()),
        permissions: permissions.clone(),
        root_cert_store_provider: None,
        fetch_dns_resolver: deno_runtime::deno_fetch::dns::Resolver::default(),
        shared_array_buffer_store: None,
        compiled_wasm_module_store: None,
        // In-process V8 code cache, keyed by specifier + source hash (limits.rs).
        v8_code_cache: Some(limits::in_process_code_cache()),
        bundle_provider: None,
    };

    // Must match deno_runtime's release tag: scripts feature-detect
    // Deno.version.deno. deno_runtime 0.265.0 == Deno v2.9.5.
    const DENO_VERSION: &str = "2.9.5";

    let main_bootstrap = BootstrapOptions {
        deno_version: DENO_VERSION.to_string(),
        user_agent: format!(
            "libdeno/{}/Deno/{}",
            env!("CARGO_PKG_VERSION"),
            DENO_VERSION
        ),
        has_node_modules_dir,
        location: Some(main_module.clone()),
        args: options.args.clone(),
        unstable_features: unstable_ids,
        // fork() IPC pipe; gated on the marker captured at run() entry (limits.rs).
        node_ipc_init: limits::node_ipc_init(),
        ..Default::default()
    };

    // Factory for `new Worker(...)`; nested workers reuse the same loader,
    // services and snapshot, and inherit the main worker's heap cap.
    let create_web_worker_cb: Arc<deno_runtime::ops::worker_host::CreateWebWorkerCb> =
        create_web_worker_factory(
            blob_store,
            broadcast_channel,
            feature_checker,
            fs.clone(),
            services.clone(),
            MainInspectorSessionChannel::default(),
            main_bootstrap.clone(),
            options.max_heap_bytes,
        )?;

    let worker_options = WorkerOptions {
        bootstrap: main_bootstrap,
        create_web_worker_cb,
        extensions: vec![],
        startup_snapshot: Some(STARTUP_SNAPSHOT),
        residual_lazy_js_sources: RESIDUAL_LAZY_JS,
        residual_lazy_esm_sources: RESIDUAL_LAZY_ESM,
        create_params: limits::isolate_create_params(options.max_heap_bytes),
        ..Default::default()
    };

    let mut worker =
        MainWorker::bootstrap_from_options(&main_module, worker_services, worker_options);

    // Intercept Deno.exit: a WatcherExitHandle in the OpState makes op_exit
    // terminate the isolate (the CLI's --watch path); ExitCode op state carries n.
    let isolate_handle = worker.js_runtime.v8_isolate().thread_safe_handle();
    worker
        .js_runtime
        .op_state()
        .borrow_mut()
        .put(deno_runtime::deno_os::WatcherExitHandle(
            isolate_handle.clone(),
        ));

    let run_result = match limits::run_worker(
        &mut worker,
        &main_module,
        options.execution_deadline,
        isolate_handle.clone(),
    )
    .await
    {
        Ok(result) => result,
        // Deadline fired: isolate terminated; cwd lock releases on return.
        Err(deadline) => {
            return Err(LibdenoError::Timeout(format!(
                "execution deadline of {deadline:?} exceeded; isolate terminated"
            )))
        }
    };

    let exit_code = match run_result {
        Ok(()) => worker.exit_code(),
        Err(_) if crate::runtime::has_watcher_exited(&worker) => worker.exit_code(),
        Err(e) => return Err(e),
    };
    // Cache the resolved npm snapshot (managed, no lockfile) only now: the
    // graph build has populated the resolution, so the snapshot is real.
    services.save_npm_snapshot_cache();
    Ok(exit_code)
}

/// Resolve the entry module: a file path, or a directory / package.json whose
/// `main` (default `index.js`) is used.
fn resolve_entry(path: &Path, cwd: &Path) -> Result<ModuleSpecifier, AnyError> {
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    };
    let file_path = if path.is_dir() {
        let pkg = path.join("package.json");
        if pkg.exists() {
            package_main(&pkg)?
        } else {
            path.join("index.js")
        }
    } else if path.file_name().and_then(|n| n.to_str()) == Some("package.json") {
        package_main(&path)?
    } else {
        path
    };
    ModuleSpecifier::from_file_path(&file_path)
        .map_err(|_| deno_core::anyhow::anyhow!("Invalid entry file path: {}", file_path.display()))
}

fn package_main(pkg_path: &Path) -> Result<PathBuf, AnyError> {
    let text = std::fs::read_to_string(pkg_path)?;
    let json: deno_core::serde_json::Value = deno_core::serde_json::from_str(&text)?;
    let main = json
        .get("main")
        .and_then(|v| v.as_str())
        .unwrap_or("index.js");
    let dir = pkg_path.parent().unwrap_or(Path::new("."));
    let main_path = dir.join(main);
    // Reject `main` values that escape the package directory. `Path::join`
    // replaces the base for absolute paths (strip_prefix fails, caught
    // directly); relative `..` components are normalized lexically — a `..`
    // that walks back into the package (`lib/../index.js`) is fine, one that
    // pops above `dir` (`../escape.js`) is not. (Symlinked components are not
    // resolved: the entry directory is host-selected, so this is a sanity
    // guard, not a boundary.)
    use std::path::Component;
    let escaped = match main_path.strip_prefix(dir) {
        Err(_) => true,
        Ok(rest) => {
            let mut depth: i64 = 0;
            let mut escaped = false;
            for c in rest.components() {
                match c {
                    Component::Normal(_) => depth += 1,
                    Component::CurDir => {}
                    Component::ParentDir => {
                        if depth == 0 {
                            escaped = true;
                            break;
                        }
                        depth -= 1;
                    }
                    Component::RootDir | Component::Prefix(_) => {
                        escaped = true;
                        break;
                    }
                }
            }
            escaped
        }
    };
    if escaped {
        return Err(deno_core::anyhow::anyhow!(
            "package.json `main` field {main:?} escapes the package directory"
        ));
    }
    Ok(main_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("libdeno-test-{}-{}", std::process::id(), name));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn resolve_entry_file() {
        let dir = temp_dir("entry-file");
        let file = dir.join("app.js");
        std::fs::write(&file, "").unwrap();
        let spec = resolve_entry(&file, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), file);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_directory_uses_package_main() {
        let dir = temp_dir("entry-dir-pkg");
        std::fs::write(
            dir.join("package.json"),
            r#"{"name":"app","main":"src/main.js"}"#,
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(dir.join("src/main.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("src/main.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_directory_defaults_to_index_js() {
        let dir = temp_dir("entry-dir-default");
        std::fs::write(dir.join("index.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("index.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_package_json_directly() {
        let dir = temp_dir("entry-pkgjson");
        std::fs::write(dir.join("package.json"), r#"{"main":"lib/index.js"}"#).unwrap();
        std::fs::create_dir_all(dir.join("lib")).unwrap();
        std::fs::write(dir.join("lib/index.js"), "").unwrap();
        let spec = resolve_entry(&dir.join("package.json"), &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("lib/index.js"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_entry_relative_path_joins_cwd() {
        let dir = temp_dir("entry-relative");
        std::fs::write(dir.join("app.ts"), "").unwrap();
        let spec = resolve_entry(Path::new("app.ts"), &dir).unwrap();
        assert_eq!(spec.to_file_path().unwrap(), dir.join("app.ts"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_escaping_the_package_dir_is_rejected() {
        let dir = temp_dir("pkg-escape");
        std::fs::write(dir.join("package.json"), r#"{"main":"../escape.js"}"#).unwrap();
        let err = resolve_entry(&dir, &dir).unwrap_err();
        assert!(
            err.to_string().contains("escapes"),
            "expected an escape rejection, got: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_internal_dotdot_is_allowed() {
        // A `..` that normalizes back inside the package (`src/../lib/index.js`)
        // is not an escape: the guard rejects only paths that pop above the
        // package directory, not every ParentDir component.
        let dir = temp_dir("pkg-internal-dotdot");
        std::fs::write(
            dir.join("package.json"),
            r#"{"main":"src/../lib/index.js"}"#,
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("lib")).unwrap();
        std::fs::write(dir.join("lib/index.js"), "").unwrap();
        let spec = resolve_entry(&dir, &dir).unwrap();
        assert_eq!(
            spec.to_file_path().unwrap(),
            dir.join("src/../lib/index.js")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn package_main_absolute_main_is_rejected() {
        // `Path::join` replaces the base for absolute paths, so an absolute
        // `main` must be rejected as an escape (strip_prefix fails).
        let dir = temp_dir("pkg-abs-main");
        std::fs::write(dir.join("package.json"), r#"{"main":"/etc/passwd"}"#).unwrap();
        let err = resolve_entry(&dir, &dir).unwrap_err();
        assert!(
            err.to_string().contains("escapes"),
            "expected an escape rejection, got: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
