// Subprocess execution mode: runs a script in a child process so that
// `Deno.exit(n)` or a hard runtime failure terminates only the child while
// the host process keeps running.

use std::path::Path;
use std::path::PathBuf;

use crate::limits::LIBDENO_SPAWNED_IPC;
use crate::run;
use crate::LibdenoError;
use crate::LibdenoOptions;

/// Environment variable marking a process spawned by [`run_in_subprocess`].
const LIBDENO_CHILD_MODE: &str = "LIBDENO_CHILD_MODE";

/// Environment variable carrying the per-run auth token a child must present
/// to prove it was spawned by [`run_in_subprocess`].
const LIBDENO_CHILD_TOKEN: &str = "LIBDENO_CHILD_TOKEN";

/// Environment variable overriding the executable [`run_in_subprocess`]
/// spawns (defaults to the current executable). Lets tests point the child
/// run at a dedicated host binary.
const LIBDENO_HOST_EXE: &str = "LIBDENO_HOST_EXE";

/// Request payload serialized to the child process's stdin by
/// [`run_in_subprocess`]. The `token` must match the [`LIBDENO_CHILD_TOKEN`]
/// environment variable the parent set on the child; without it the child
/// refuses to run.
///
/// `entry` and `cwd` serialize as `PathBuf`, so a non-UTF-8 path fails the
/// serialization (an error the parent surfaces) rather than being silently
/// mangled by `to_string_lossy`.
#[derive(serde::Serialize, serde::Deserialize)]
struct ChildRunRequest {
    entry: PathBuf,
    permissions: Vec<String>,
    allow_all_permissions: bool,
    prompt: bool,
    args: Vec<String>,
    cwd: PathBuf,
    /// Per-run auth token, verified against [`LIBDENO_CHILD_TOKEN`].
    token: String,
    /// Safety options are forwarded verbatim: a host that bounds an
    /// untrusted script with `max_heap_bytes` / `execution_deadline` (or
    /// shrinks `features` to the default unstable set) must get the same
    /// bounds in child mode — the subprocess entry point exists for
    /// isolation, and silently dropping these would run the child unbounded
    /// on the full unstable API surface. The capture flags are deliberately
    /// NOT forwarded: the child inherits the parent's fds, so captured
    /// output in the child would be computed and discarded — capture
    /// belongs on the parent side (redirect its own fds around the call).
    features: Option<Vec<String>>,
    max_heap_bytes: Option<usize>,
    execution_deadline: Option<std::time::Duration>,
}

/// Generates a fresh 32-hex-char auth token for a child run.
///
/// The token authenticates the same-user subprocess handshake, not a security
/// boundary (see [`run_in_subprocess`]); it still needs real entropy so a
/// stdin-only third party cannot guess it.
fn child_token() -> Result<String, LibdenoError> {
    let mut buf = [0u8; 16];
    getrandom::fill(&mut buf).map_err(|e| LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)))?;
    Ok(buf.iter().map(|b| format!("{b:02x}")).collect())
}

/// Constant-time token compare: both tokens are the same fixed format
/// (32 hex chars) generated by [`child_token`], so a plain byte XOR fold over
/// the equal-length representations avoids the timing channel of `!=` on
/// attacker-influenced data. Not a security boundary (same-user handshake) —
/// cheap defense, not the load-bearing check.
fn token_matches(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    // Fail closed on empty tokens: a legitimate token is always the 32-hex
    // string child_token() generates, so an empty token (e.g. a hand-rolled
    // host with LIBDENO_CHILD_TOKEN set-but-empty) must never authenticate.
    !a.is_empty()
        && a.len() == b.len()
        && a.iter().zip(b).fold(0u8, |acc, (x, y)| acc | (x ^ y)) == 0
}

/// Runs `entry` in a child process and returns its exit code.
///
/// The script runs inside a subprocess, so `Deno.exit(n)` or a hard runtime
/// failure terminates only the child — the host process keeps running. The
/// host binary must call [`maybe_handle_child_mode`] at the very start of its
/// `main()` for the child request to be serviced.
///
/// The child inherits stdout/stderr, so script output still appears. Entry,
/// permissions, prompt, args and cwd are passed over stdin as JSON, together
/// with a fresh per-run auth `token`. The same token is handed to the child
/// via the `LIBDENO_CHILD_TOKEN` environment variable; the child refuses to
/// run unless the request token matches, so a process that can set
/// `LIBDENO_CHILD_MODE` and write the child's stdin cannot inject a request
/// of its own.
///
/// The payload write is bounded at 10s (aligned with the child side's stdin
/// deadline): a host that never services child mode (never reads stdin)
/// otherwise blocks the write once the pipe buffer fills; on timeout the
/// child is killed and `LibdenoError::Timeout` is returned. Note that a
/// small payload against a non-servicing host still succeeds the write — the
/// bound only protects once the request exceeds the pipe buffer.
///
/// # Security
///
/// Child mode turns a host process into an arbitrary-code-execution server
/// for anything that can set the two environment variables and write stdin.
/// Do NOT run a host with child mode enabled under elevated privileges
/// (setuid, service daemons, admin/root): the token authenticates only the
/// same user's subprocess, it is not a privilege boundary.
pub fn run_in_subprocess(
    entry: impl AsRef<Path>,
    options: &LibdenoOptions,
) -> Result<i32, LibdenoError> {
    // In-process runs never switch the process cwd (cwd is a resolution base
    // only), so the child's cwd can be pinned from a plain read with no
    // synchronization. The lock is NOT held across child.wait() — that would
    // deadlock hosts that run long-lived children (plugins/daemons): the
    // first child would hold a process-global lock forever and block every
    // later run_in_subprocess or run() call in the same process.
    let token = child_token()?;
    let (payload, mut child) = {
        let cwd = options.cwd.clone().unwrap_or(std::env::current_dir()?);
        let request = ChildRunRequest {
            entry: entry.as_ref().to_path_buf(),
            permissions: options.permissions.clone(),
            allow_all_permissions: options.allow_all_permissions,
            prompt: options.prompt,
            args: options.args.clone(),
            cwd: cwd.clone(),
            token: token.clone(),
            features: options.features.clone(),
            max_heap_bytes: options.max_heap_bytes,
            execution_deadline: options.execution_deadline,
        };
        let payload = deno_core::serde_json::to_vec(&request)
            .map_err(|e| LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)))?;
        let exe = std::env::var_os(LIBDENO_HOST_EXE)
            .map(PathBuf::from)
            .unwrap_or(std::env::current_exe()?);
        let child = std::process::Command::new(exe)
            .env(LIBDENO_CHILD_MODE, "1")
            .env(LIBDENO_SPAWNED_IPC, "1")
            .env(LIBDENO_CHILD_TOKEN, &token)
            .current_dir(&cwd)
            .stdin(std::process::Stdio::piped())
            .spawn()
            .map_err(LibdenoError::Io)?;
        (payload, child)
    };
    {
        use std::io::Write;
        let write_result = match child.stdin.take() {
            Some(mut stdin) => {
                // The payload write can block forever when the host never
                // services child mode (a host that does not call
                // maybe_handle_child_mode never reads stdin): once the pipe
                // buffer (~64 KiB) fills, write_all blocks until the child
                // reads. Move the blocking write to a detached thread and
                // bound the wait at 10s (aligned with the child side's own
                // stdin deadline). On timeout the child is killed (closing its
                // pipe end, which unblocks the writer) and a Timeout error is
                // surfaced. The thread is deliberately not joined: after the
                // kill it can still be blocked inside write_all, and the
                // process reaps it at exit.
                let (tx, rx) = std::sync::mpsc::channel::<std::io::Result<()>>();
                std::thread::spawn(move || {
                    let _ = tx.send(stdin.write_all(&payload));
                });
                match rx.recv_timeout(std::time::Duration::from_secs(10)) {
                    Ok(Ok(())) => Ok(()),
                    Ok(Err(e)) => Err(LibdenoError::Io(e)),
                    Err(std::sync::mpsc::RecvTimeoutError::Timeout) => Err(LibdenoError::Timeout(
                        "subprocess handshake timed out after 10s: \
                             host did not service child mode (stdin not read)"
                            .to_string(),
                    )),
                    Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                        Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                            "child stdin writer terminated unexpectedly"
                        )))
                    }
                }
            }
            None => Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                "child has no stdin"
            ))),
        };
        if let Err(e) = write_result {
            // Don't leak the child (or a zombie) on this error path: it may be
            // blocked reading stdin or already dead. If it already exited
            // (e.g. its 10s stdin deadline fired, or it was killed), the write
            // failure is downstream of that — surface the child's state
            // instead of a bare Broken pipe.
            match child.try_wait() {
                Ok(Some(status)) => {
                    return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                        "child exited with {status} before accepting the run request \
                         (request write failed: {e})"
                    )));
                }
                _ => {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(e);
                }
            }
        }
    }
    // The writer thread dropped the last handle to the child's stdin after the
    // payload write, so a script reading process.stdin sees EOF instead of
    // blocking forever on the still-open pipe.
    let status = child.wait().map_err(LibdenoError::Io)?;
    Ok(status.code().unwrap_or(1))
}

/// Runs `entry` in a child process and returns the exit code together with
/// the child's captured stdout/stderr — the subprocess answer to output
/// capture.
///
/// Unlike in-process capture — which is fd-level redirection of the
/// process-global stdout/stderr and therefore **exclusive** (any concurrent
/// run is rejected with `Configuration`, and it does not work on Windows) —
/// this capture is per-process: the child's own fds are piped back to the
/// parent and read concurrently with `wait()` (a verbose child can never
/// deadlock on a full pipe buffer). It runs in parallel with any other run,
/// on every platform, Windows included.
///
/// `capture_stdout` / `capture_stderr` are always implied (both streams are
/// returned); `max_capture_bytes` caps each stream — excess is dropped (the
/// reader keeps draining so the child never blocks) and
/// [`RunOutput::capture_truncated`](crate::RunOutput::capture_truncated) is
/// set. Every other option (permissions, features, max_heap_bytes,
/// execution_deadline, ...) behaves exactly as in [`run_in_subprocess`].
pub fn run_in_subprocess_with_output(
    entry: impl AsRef<Path>,
    options: &LibdenoOptions,
) -> Result<crate::RunOutput, LibdenoError> {
    let token = child_token()?;
    let (payload, mut child) = {
        let cwd = options.cwd.clone().unwrap_or(std::env::current_dir()?);
        let request = ChildRunRequest {
            entry: entry.as_ref().to_path_buf(),
            permissions: options.permissions.clone(),
            allow_all_permissions: options.allow_all_permissions,
            prompt: options.prompt,
            args: options.args.clone(),
            cwd: cwd.clone(),
            token: token.clone(),
            features: options.features.clone(),
            max_heap_bytes: options.max_heap_bytes,
            execution_deadline: options.execution_deadline,
        };
        let payload = deno_core::serde_json::to_vec(&request)
            .map_err(|e| LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)))?;
        let exe = std::env::var_os(LIBDENO_HOST_EXE)
            .map(PathBuf::from)
            .unwrap_or(std::env::current_exe()?);
        let child = std::process::Command::new(exe)
            .env(LIBDENO_CHILD_MODE, "1")
            .env(LIBDENO_SPAWNED_IPC, "1")
            .env(LIBDENO_CHILD_TOKEN, &token)
            .current_dir(&cwd)
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .map_err(LibdenoError::Io)?;
        (payload, child)
    };
    {
        use std::io::Write;
        // Same bounded handshake as run_in_subprocess: a host that never
        // services child mode would block the payload write forever once the
        // pipe buffer fills, so the write runs on a detached thread with a
        // 10s bound, and the child is killed on timeout.
        let write_result = match child.stdin.take() {
            Some(mut stdin) => {
                let (tx, rx) = std::sync::mpsc::channel::<std::io::Result<()>>();
                std::thread::spawn(move || {
                    let _ = tx.send(stdin.write_all(&payload));
                });
                match rx.recv_timeout(std::time::Duration::from_secs(10)) {
                    Ok(Ok(())) => Ok(()),
                    Ok(Err(e)) => Err(LibdenoError::Io(e)),
                    Err(std::sync::mpsc::RecvTimeoutError::Timeout) => Err(LibdenoError::Timeout(
                        "subprocess handshake timed out after 10s: \
                             host did not service child mode (stdin not read)"
                            .to_string(),
                    )),
                    Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                        Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                            "child stdin writer terminated unexpectedly"
                        )))
                    }
                }
            }
            None => Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                "child has no stdin"
            ))),
        };
        if let Err(e) = write_result {
            match child.try_wait() {
                Ok(Some(status)) => {
                    return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                        "child exited with {status} before accepting the run request \
                         (request write failed: {e})"
                    )));
                }
                _ => {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(e);
                }
            }
        }
    }
    // Drain both pipes concurrently with wait(): a child that fills a pipe
    // buffer blocks on write, so the parent must read while waiting or the
    // run deadlocks. Each stream keeps the first `max_capture_bytes` bytes
    // and keeps draining (dropping) the rest so the child never blocks; a
    // truncated stream sets the flag, mirroring in-process capture.
    let max = options.max_capture_bytes.unwrap_or(usize::MAX);
    let stdout_handle = child
        .stdout
        .take()
        .map(|pipe| std::thread::spawn(move || drain_pipe(pipe, max)));
    let stderr_handle = child
        .stderr
        .take()
        .map(|pipe| std::thread::spawn(move || drain_pipe(pipe, max)));
    let status = child.wait().map_err(LibdenoError::Io)?;
    let (stdout, stdout_truncated) = stdout_handle
        .map(|h| h.join().unwrap_or_default())
        .unwrap_or_default();
    let (stderr, stderr_truncated) = stderr_handle
        .map(|h| h.join().unwrap_or_default())
        .unwrap_or_default();
    Ok(crate::RunOutput {
        exit_code: status.code().unwrap_or(1),
        stdout,
        stderr,
        capture_truncated: stdout_truncated || stderr_truncated,
    })
}

/// Reads a child pipe to EOF, keeping the first `max` bytes; excess is
/// drained and dropped (a truncated stream still unblocks the child). Read
/// errors are tolerated (best-effort capture, like in-process capture).
fn drain_pipe<R: std::io::Read>(mut pipe: R, max: usize) -> (Vec<u8>, bool) {
    let mut out = Vec::new();
    let mut truncated = false;
    let mut buf = [0u8; 64 * 1024];
    loop {
        match pipe.read(&mut buf) {
            Ok(0) => break,
            Ok(n) => {
                let room = max.saturating_sub(out.len());
                let keep = room.min(n);
                if keep > 0 {
                    out.extend_from_slice(&buf[..keep]);
                }
                if n > keep {
                    truncated = true;
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
            Err(_) => break,
        }
    }
    (out, truncated)
}

/// Services a child-run request when this process was spawned by
/// [`run_in_subprocess`].
///
/// Call this at the very start of `main()`. For a normal host launch it
/// returns `false` immediately; in child mode it executes the requested
/// script and exits the process with the script's exit code (including
/// `Deno.exit(n)`), so it does not return.
///
/// Child mode is serviced only when both `LIBDENO_CHILD_MODE` and
/// `LIBDENO_CHILD_TOKEN` are set and the request's token matches the
/// environment token — the handshake [`run_in_subprocess`] sets up. A missing
/// or mismatched token exits with an error rather than falling through to a
/// host run, which could otherwise execute the host at elevated privilege.
///
/// # Security
///
/// A process in child mode executes whatever request arrives on its stdin,
/// authenticated only by the token. Never run a host with child mode enabled
/// under elevated privileges (setuid, service daemon, admin/root).
///
/// The stdin request read is capped at 10 seconds; a caller that sets
/// `LIBDENO_CHILD_MODE` but never sends (or never closes) stdin gets the
/// process exited rather than blocked forever.
///
/// In child mode the child's stdin is a pipe (consumed by the request JSON),
/// so the interactive prompter's terminal check denies without reading —
/// `prompt: true` in a child is equivalent to fail-closed deny; real
/// interaction only makes sense for in-process `run`.
pub fn maybe_handle_child_mode() -> bool {
    // Only an explicit `LIBDENO_CHILD_MODE=1` enters child mode; a stale or
    // accidental value must not turn the host into a request server.
    if std::env::var(LIBDENO_CHILD_MODE).as_deref() != Ok("1") {
        return false;
    }
    let Some(env_token) = std::env::var_os(LIBDENO_CHILD_TOKEN) else {
        eprintln!(
            "libdeno: {LIBDENO_CHILD_MODE} is set but {LIBDENO_CHILD_TOKEN} is missing; \
             refusing to service an unauthenticated child request"
        );
        std::process::exit(1);
    };
    let result: Result<i32, LibdenoError> = (|| {
        // The child-mode request read is bounded: a caller that sets LIBDENO_CHILD_MODE
        // but never writes (or never closes) stdin must not pin this process forever.
        // Stdin is a 'static handle and Send, so the blocking read moves to a
        // dedicated thread and the main thread waits with a deadline.
        //
        // In the normal flow the parent writes the payload (and closes stdin)
        // before the child reaches this read, so the data is already in the
        // pipe and the 10s bound never fires. It can only false-fire in the
        // degenerate case where the parent is suspended between spawn and
        // write (SIGSTOP / debugger attach) for over 10s — then the child
        // exits 1 and the parent's write fails against a dead child with a
        // confusing Io error. Accepted trade-off for bounding an
        // attacker-held-open stdin.
        let request: ChildRunRequest = {
            let (tx, rx) =
                std::sync::mpsc::channel::<Result<ChildRunRequest, deno_core::serde_json::Error>>();
            std::thread::spawn(move || {
                let _ = tx.send(deno_core::serde_json::from_reader(std::io::stdin()));
            });
            match rx.recv_timeout(std::time::Duration::from_secs(10)) {
                Ok(Ok(request)) => request,
                Ok(Err(e)) => {
                    return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(e)));
                }
                Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                    eprintln!(
                        "libdeno: child-mode request timed out waiting on stdin; refusing to run"
                    );
                    std::process::exit(1);
                }
                Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                    return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                        "child-mode stdin reader terminated unexpectedly"
                    )));
                }
            }
        };
        if !token_matches(&request.token, &env_token.to_string_lossy()) {
            return Err(LibdenoError::Runtime(deno_core::anyhow::anyhow!(
                "child request token does not match {LIBDENO_CHILD_TOKEN}"
            )));
        }
        let options = LibdenoOptions {
            permissions: request.permissions,
            allow_all_permissions: request.allow_all_permissions,
            prompt: request.prompt,
            args: request.args,
            cwd: Some(request.cwd),
            // Forwarded safety options: the child must run under the same
            // bounds the host configured (see ChildRunRequest). `Some([])`
            // (the minimal surface, worker-options only) and `None` (the
            // full default unstable surface) survive the round-trip
            // distinctly — serde keeps `[]` vs `null` apart.
            features: request.features,
            max_heap_bytes: request.max_heap_bytes,
            execution_deadline: request.execution_deadline,
            ..Default::default()
        };
        // The request has been authenticated; strip the child-mode markers
        // before running so any subprocess the script spawns (Deno.Command,
        // child_process.spawn, exec) inherits a clean environment. Without
        // this, every grandchild enters child mode with a consumed stdin and
        // dies with an unactionable "stdin reader terminated" error — the
        // exact break that would hit a plugin shelling out to git/compilers.
        std::env::remove_var(LIBDENO_CHILD_MODE);
        std::env::remove_var(LIBDENO_CHILD_TOKEN);
        run(&request.entry, &options)
    })();
    match result {
        Ok(code) => std::process::exit(code),
        Err(e) => {
            eprintln!("libdeno child run failed: {e}");
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::token_matches;

    #[test]
    fn token_matches_compares_tokens() {
        let token = "0123456789abcdef0123456789abcdef";
        assert!(token_matches(token, token));
        // One byte difference must fail.
        assert!(!token_matches(token, "0123456789abcdef0123456789abcdee"));
        // Length mismatch fails closed without panicking.
        assert!(!token_matches(token, "abc"));
        assert!(!token_matches("abc", token));
        // Empty tokens fail closed: a legitimate token is never empty.
        assert!(!token_matches("", ""));
        assert!(!token_matches(token, ""));
    }
}
